CHROMIUM: Export drm_mode_mmap_dumb_ioctl
drm_mode_mmap_dumb_ioctl() is now referenced from vgem code and thus
needs to be exported. This avoids the following build error, seen for example
when trying to build arm:allmodconfig.

ERROR: "drm_mode_mmap_dumb_ioctl" [drivers/gpu/drm/vgem/vgem.ko] undefined!

BUG=chromium:591626
TEST=Build arm:allmodconfig

Fixes: 4281b9fe7ef4 ("CHROMIUM: drm/vgem: add DRM_IOCTL_VGEM_MODE_MAP_DUMB for render nodes")
Change-Id: I475c7c1ac7086ca07704d0f58369f3d402d76db4
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/339075
Reviewed-by: Brian Norris <briannorris@chromium.org>